--- Makefile.orig	2016-02-18 19:25:49.941634933 +0900
+++ Makefile	2016-02-18 19:27:00.529760280 +0900
@@ -13,7 +13,7 @@
 # -------------------------
 
 
-RDKIT=$(RDBASE)
+RDKIT=/opt/rdkit-python
 
 
 ifeq ($(USE_INCHI),1)
@@ -51,7 +51,7 @@
 
 SHLIB_LINK += ${THREADLIBS}
 
-PG_CPPFLAGS = -I${BOOSTHOME}/include -I${RDKIT}/Code -DRDKITVER='"007300"' ${AVALONFLAGS} ${INCHIFLAGS} ${POPCOUNTFLAGS}
+PG_CPPFLAGS = -I${BOOSTHOME}/include -I${RDKIT}/include/rdkit -DRDKITVER='"007300"' ${AVALONFLAGS} ${INCHIFLAGS} ${POPCOUNTFLAGS}
 
 CPLUSPLUSFLAGS = $(filter-out -fexcess-precision=standard -Wmissing-prototypes -Wdeclaration-after-statement, $(CFLAGS))
 CPLUSPLUSFLAGS += -Wno-unused-function 
