--- Makefile.orig	2015-07-27 23:10:32.673383164 +0900
+++ Makefile	2015-07-27 23:10:38.623383473 +0900
@@ -44,7 +44,6 @@
 	install -m755 $(TARGET_LIB) $(PREFIX)/lib/$(TARGET_LIB).$(VER)
 	ln -sf $(PREFIX)/lib/$(TARGET_LIB).$(VER) $(PREFIX)/lib/$(TARGET_LIB).$(MAJOR)
 	ln -sf $(PREFIX)/lib/$(TARGET_LIB).$(MAJOR) $(PREFIX)/lib/$(TARGET_LIB)
-	ldconfig
 
 install-headers:
 	mkdir -p $(DEST_HEADER)
