--- a/makefile	2016-08-09 18:53:33.422867848 +0900
+++ b/makefile	2016-08-09 18:53:37.446301874 +0900
@@ -109,7 +109,7 @@
 	@./test/unit_test
 	@$(RBT_ROOT)/bin/rbdock -r1YET_test.prm -i ./test/RBT_HOME/1YET_c.sd -p dock.prm -n 1 -s 48151623 -o 1YET_test_out > 1YET_test_out.log
 	@mv 1YET_test_out.log 1YET_test_out.sd ./test/RBT_HOME/
-	@python ./test/RBT_HOME/check_test.py ./test/RBT_HOME/1YET_reference_out.sd ./test/RBT_HOME/1YET_test_out.sd
+	@python2 ./test/RBT_HOME/check_test.py ./test/RBT_HOME/1YET_reference_out.sd ./test/RBT_HOME/1YET_test_out.sd
 
 ./test/unit_test:
 	$(warning $@ executable not found)
