--- a/src/Makefile	2015-06-06 01:21:08.000000000 +0900
+++ b/src/Makefile	2016-05-21 04:31:56.055424387 +0900
@@ -8,7 +8,7 @@
 
 
 
-HOST := cpuhost
+HOST := gpuhost
 
 ifeq ($(HOST), cpuhost)
         LIBPATH += -L/usr/lib/x86_64-redhat-linux5E/lib64
@@ -18,9 +18,9 @@
 	TARGET_DEVICE := $(TARGET_MIC)
 
 else ifeq ($(HOST), gpuhost)
-	LIBPATH += -L/usr/local/packages/cuda/6.5/lib64
+	LIBPATH += -L/opt/cuda/lib64
 	TARGET_DEVICE := $(TARGET_GPU)
-	GPU := K20X
+	GPU := GTX980
         NGPU := 1
 
 else ifeq ($(HOST), ece)
@@ -117,6 +117,7 @@
 	DEVFLAGS += -O3
 	DEVFLAGS += $(DMARCRO_GPU)
 	DEVFLAGS += -Xptxas -v
+	DEVFLAGS += -Xcompiler -std=c++98
 #	DEVFLAGS += #-Xcompiler -fopenmp
 #	DEVFLAGS += -keep --keep-dir tmp -G --source-in-ptx
 #
